# Generated by Django 2.0.7 on 2018-09-22 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='billingprofile',
            old_name='activate',
            new_name='active',
        ),
    ]
