# Generated by Django 2.0.7 on 2018-08-03 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20180801_1802'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': 'created', 'ordering': ('-created',)},
        ),
    ]
